[build]
  publish = "docs/sachiko"
  command = ""
  ignore = "exit 0"

[[headers]]
  for = "*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=86400"
