[build]
  publish = "docs/sachiko"
  command = ""

[build.environment]
  NETLIFY_SKIP_DEPENDENCY_INSTALLATION = "true"

[[headers]]
  for = "*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=86400"
